package com.consystec.sc.ca.ws.util;


public class Conf {
	private Conf(){}
    // parametros configurables utilizados por servicios
    public static final String CANTIDAD_MINUTOS_SESION = "CANT_MINUTOS_SESION";
    public static final String DIFERENCIA_HORARIO = "DIFERENCIA_HORARIO";
    public static final String GRUPO_CONFIG_SIDRA = "CONFIG_SIDRA";
    public static final String URI_SOCKET_VENTA = "URI_SOCKET_VENTA";

    public static final String ESTADO_ALTA = "estado_alta";
    public static final String ESTADO_BAJA = "estado_baja";
    public static final String PAIS_DEFAULT = "pais_default";
    public static final String ESTADO_ALTA_TXT = "estado_alta_txt";

    /* PARAMETROS PARA DETERMINAR SI REQUIERE PAGO UNA ORDEN */
    public static final String REQUIERE_PAGO_SI = "requiere_pago_si";
    public static final String REQUIERE_PAGO_NO = "requiere_pago_no";
    public static final String REQUIERE_PAGO = "requiere_pago";
    public static final String NO_REQUIERE_PAGO = "no_requiere_pago";

    /* Formatos de fecha */
    public static final String TXT_FORMATO_FECHA = "dd/MM/yyyy";
 
    public static final String LONGITUD_NUMERO = "LONGITUD_NUMERO";
    public static final String LONG_IDENTIFICACION = "LONG_IDENTIFICACION";

    public static final int LONG_CODPAIS = 3;
    public static final int LONG_TOKEN = 256;
    public static final int LONG_USUARIO = 50;

    /*
     * PARAMETROS PARA OBTENER ETIQUETAS O VALORES DE LA TABLA PARAMETROS O
     * ESTADOS DE ORDEN
     */
    public static final int TIPO_PARAMETRO = 1;
    public static final int TIPO_ESTADO_ORDEN = 2;
    public static final int TIPO_ESTADO_LOTE = 3;

    /* PARAMETRO DE APLICACION */
    public static final String NOMBRE_APLICACION = "APPMOVIL";
    
    //Configuraciones de LOG
    public static final String CARPETA_LOG = "logs";
    public static final String GRUPO_REGIONAL_CONFIG_LOG4J = "REGIONAL_CONFIG_LOG4J";
    public static final String LEVEL_LOG4J = "LEVEL_LOG4J";
    public static final String PATH_REGIONAL_LOG4J = "PATH_REGIONAL_LOG4J";
    public static final String PATH_TGT101_LOG4J = "URL_TGT101";
    public static final String PATH_TGT103_LOG4J = "URL_TGT103";
    public static final String IP_TGT101_LOG4J = "IP_TGT101";
    public static final String IP_TGT103_LOG4J = "IP_TGT103";
    public static final String LOG4J_OFF = "OFF";
    public static final String LOG4J_FATAL = "FATAL";
    public static final String LOG4J_ERROR = "ERROR";
    public static final String LOG4J_WARN = "WARN";
    public static final String LOG4J_INFO = "INFO";
    public static final String LOG4J_DEBUG = "DEBUG";
    public static final String LOG4J_TRACE = "TRACE";
    public static final String LOG4J_ALL = "ALL";

    /* PARAMETRO SERVICIO PAGO */
    public static final int YEAR = 2000;
    public static final int MONTH = -1;

    /* PARA FTP DE CARGA DE IMAGENES */
    public static final String IP = "173.15.2.73";
    public static final String DIR = "ImageUpload";
    public static final String PUERTO = "21";
    public static final String USUARIO = "consystec";
    public static final String CLAVE = "consystec";

    public static final String FTPNUEVO = "NUEVO";
    public static final String FTPBORRAR = "BORRAR";

    /* PARA LOGIN */
    public static final String PERFIL_VENDEDOR = "perfil_vendedor";
    public static final String NOMBRE_APPMOVIL = "nombre_appmovil";

    /* PARAMETRO PARA METODOS DE SERVICIOS REST */
    public static final int METODO_GET = 0;
    public static final int METODO_POST = 1;
    public static final int METODO_PUT = 2;
    public static final int METODO_DELETE = 3;

    /* CONSTANTES PARA URL DE SERVICIOS WEB */
    public static final String SERVICIO_LOCAL_CREARCATALOGO = "SERVICIO_LOCAL_CREARCATALOGO";
    public static final String SERVICIO_LOCAL_MODCATALOGO = "SERVICIO_LOCAL_MODCATALOGO";
    public static final String SERVICIO_LOCAL_GETCATALOGO = "SERVICIO_LOCAL_GETCATALOGO";
    public static final String SERVICIO_LOCAL_DELCATALOGO = "SERVICIO_LOCAL_DELCATALOGO";
    public static final String SERVICIO_LOCAL_GETBODEGADTS = "SERVICIO_LOCAL_GETBODEGADTS";
    public static final String SERVICIO_LOCAL_CREARBODEGADTS = "SERVICIO_LOCAL_CREARBODEGADTS";
    public static final String SERVICIO_LOCAL_MODBODEGADTS = "SERVICIO_LOCAL_MODBODEGADTS";
    public static final String SERVICIO_LOCAL_BAJABODEGADTS = "SERVICIO_LOCAL_BAJABODEGADTS";
    public static final String SERVICIO_LOCAL_GETBODEGASCL = "SERVICIO_LOCAL_GETBODEGASCL";
    public static final String SERVICIO_LOCAL_MODPDV = "SERVICIO_LOCAL_MODPDV";
    public static final String SERVICIO_LOCAL_CREARPDV = "SERVICIO_LOCAL_CREARPDV";
    public static final String SERVICIO_LOCAL_CAMBIAESTADOPDV = "SERVICIO_LOCAL_CAMBIAESTADOPDV";
    public static final String SERVICIO_LOCAL_GETPDV = "SERVICIO_LOCAL_GETPDV";
    public static final String SERVICIO_LOCAL_GET_COUNT_PDV = "SERVICIO_LOCAL_GET_COUNT_PDV";
    public static final String SERVICIO_LOCAL_CARGAFILE = "SERVICIO_LOCAL_CARGAFILE";
    public static final String SERVICIO_LOCAL_GETFILE = "SERVICIO_LOCAL_GETFILE";
    public static final String SERVICIO_LOCAL_DEL_FILE = "SERVICIO_LOCAL_DEL_FILE";
    public static final String SERVICIO_LOCAL_GET_IMGSPDV = "SERVICIO_LOCAL_GET_IMGSPDV";
    public static final String SERVICIO_LOCAL_GET_PDV_DISPONIBLES = "SERVICIO_LOCAL_GET_PDV_DISPONIBLES";
    public static final String SERVICIO_LOCAL_GET_COUNT_PDV_DISPONIBLES = "SERVICIO_LOCAL_GET_COUNT_PDV_DISPONIBLES";

    // DISTRIBUIDORES
    public static final String SERVICIO_LOCAL_CREARDTS = "SERVICIO_LOCAL_CREARDTS";
    public static final String SERVICIO_LOCAL_MODDTS = "SERVICIO_LOCAL_MODDTS";
    public static final String SERVICIO_LOCAL_GETDTS = "SERVICIO_LOCAL_GETDTS";
    public static final String SERVICIO_LOCAL_BAJADTS = "SERVICIO_LOCAL_BAJADTS";

    // BODEGAS VIRTUALES Y FOLIOS
    public static final String SERVICIO_LOCAL_CREABODEGAVIRTUAL = "SERVICIO_LOCAL_CREABODEGAVIRTUAL";
    public static final String SERVICIO_LOCAL_MODBODEGAVIRTUAL = "SERVICIO_LOCAL_MODBODEGAVIRTUAL";
    public static final String SERVICIO_LOCAL_GETBODEGAVIRTUAL = "SERVICIO_LOCAL_GETBODEGAVIRTUAL";
    public static final String SERVICIO_LOCAL_ADDFOLIOVIRTUAL = "SERVICIO_LOCAL_ADDFOLIOVIRTUAL";
    public static final String SERVICIO_LOCAL_BAJAFOLIOVIRTUAL = "SERVICIO_LOCAL_BAJAFOLIOVIRTUAL";
    public static final String SERVICIO_LOCAL_GETFOLIOVIRTUAL = "SERVICIO_LOCAL_GETFOLIOVIRTUAL";
    public static final String SERVICIO_LOCAL_BAJABODEGAVIRTUAL = "SERVICIO_LOCAL_BAJABODEGAVIRTUAL";

    // FOLIOS PARA BODEGAS DTS
    public static final String SERVICIO_LOCAL_ADDFOLIOBODDTS = "SERVICIO_LOCAL_ADDFOLIOBODDTS";
    public static final String SERVICIO_LOCAL_BAJAFOLIOBODDTS = "SERVICIO_LOCAL_BAJAFOLIOBODDTS";
    public static final String SERVICIO_LOCAL_GETFOLIOBODDTS = "SERVICIO_LOCAL_GETFOLIOBODDTS";

    // PANELES
    public static final String SERVICIO_LOCAL_CREAPANEL = "SERVICIO_LOCAL_CREAPANEL";
    public static final String SERVICIO_LOCAL_MODIFICAPANEL = "SERVICIO_LOCAL_MODIFICAPANEL";
    public static final String SERVICIO_LOCAL_CAMBIAESTADOPANEL = "SERVICIO_LOCAL_CAMBIAESTADOPANEL";
    public static final String SERVICIO_LOCAL_GETPANEL_VEND = "SERVICIO_LOCAL_GETPANEL_VEND";
    public static final String SERVICIO_LOCAL_GETPANEL = "SERVICIO_LOCAL_GETPANEL";

    // RUTAS
    public static final String SERVICIO_LOCAL_CREARUTA = "SERVICIO_LOCAL_CREARUTA";
    public static final String SERVICIO_LOCAL_MODRUTA = "SERVICIO_LOCAL_MODRUTA";
    public static final String SERVICIO_LOCAL_CAMBIAESTADORUTA = "SERVICIO_LOCAL_CAMBIAESTADORUTA";
    public static final String SERVICIO_LOCAL_GETRUTA = "SERVICIO_LOCAL_GETRUTA";

    // CLIENTES
    public static final String SERVICIO_LOCAL_CREACLIENTE = "SERVICIO_LOCAL_CREACLIENTE";
    public static final String SERVICIO_LOCAL_MODCLIENTE = "SERVICIO_LOCAL_MODCLIENTE";
    public static final String SERVICIO_LOCAL_DELCLIENTE = "SERVICIO_LOCAL_DELCLIENTE";
    public static final String SERVICIO_LOCAL_GETCLIENTE = "SERVICIO_LOCAL_GETCLIENTE";

    // OFERTA COMERCIAL
    public static final String SERVICIO_LOCAL_GETARTICULO = "SERVICIO_LOCAL_GETARTICULO";
    public static final String SERVICIO_LOCAL_GETPRECIOART = "SERVICIO_LOCAL_GETPRECIOART";

    // DESCUENTOS
    public static final String SERVICIO_LOCAL_CREADESCUENTO = "SERVICIO_LOCAL_CREADESCUENTO";
    public static final String SERVICIO_LOCAL_MODDESCUENTO = "SERVICIO_LOCAL_MODDESCUENTO";
    public static final String SERVICIO_LOCAL_GETDESCUENTO = "SERVICIO_LOCAL_GETDESCUENTO";
    public static final String SERVICIO_LOCAL_BAJADESCUENTO = "SERVICIO_LOCAL_BAJADESCUENTO";
    
    public static final String SERVICIO_LOCAL_DESCUENTO_FS = "SERVICIO_LOCAL_GET_DESCUENTO_FS";
    public static final String SERVICIO_LOCAL_OFERTA_FS = "SERVICIO_LOCAL_GET_OFERTA_FS";
    

    // VERSION CATALOGOS POR PAIS
    public static final String SERVICIO_LOCAL_GETVERSIONCATALOGO = "SERVICIO_LOCAL_GETVERSIONCATALOGO";
    public static final String CATALOGOS_MOVIL = "CATALOGOS_MOVIL";

    // BUZONES
    public static final String SERVICIO_LOCAL_CREABUZON = "SERVICIO_LOCAL_CREABUZON";
    public static final String SERVICIO_LOCAL_MODBUZON = "SERVICIO_LOCAL_MODBUZON";
    public static final String SERVICIO_LOCAL_GETBUZON = "SERVICIO_LOCAL_GETBUZON";

    // INFORMACION DE PA\u00EDS
    public static final String SERVICIO_LOCAL_GETDATOSPAIS = "SERVICIO_LOCAL_GETDATOSPAIS";
    public static final String SERVICIO_LOCAL_GETIMPUESTOS = "SERVICIO_LOCAL_GETIMPUESTOS";

    // SOLICITUDES WORK FLOW
    public static final String SERVICIO_LOCAL_CREASOLICITUD = "SERVICIO_LOCAL_CREASOLICITUD";
    public static final String SERVICIO_LOCAL_GETSOLICITUD = "SERVICIO_LOCAL_GETSOLICITUD";
    public static final String SERVICIO_LOCAL_MODSOLICITUD = "SERVICIO_LOCAL_MODSOLICITUD";

    // USUARIOS BUZON
    public static final String SERVICIO_LOCAL_CREABUZONUSER = "SERVICIO_LOCAL_CREABUZONUSER";
    public static final String SERVICIO_LOCAL_MODBUZONUSER = "SERVICIO_LOCAL_MODBUZONUSER";
    public static final String SERVICIO_LOCAL_GETBUZONUSER = "SERVICIO_LOCAL_GETBUZONUSER";
    public static final String SERVICIO_LOCAL_DELBUZONUSER = "SERVICIO_LOCAL_DELBUZONUSER";

    // INVENTARIO
    public static final String SERVICIO_LOCAL_GETINVENTARIO = "SERVICIO_LOCAL_GETINVENTARIO";
    public static final String SERVICIO_LOCAL_GET_CANTINV = "SERVICIO_LOCAL_GET_CANTINV";
    public static final String SERVICIO_LOCAL_GET_SERIES = "SERVICIO_LOCAL_GET_SERIES";
    public static final String SERVICIO_LOCAL_GETINVENTARIO_MOVIL = "SERVICIO_LOCAL_GETINVENTARIO_MOVIL";

    // TRASLADO
    public static final String SERVICIO_LOCAL_CREATRASLADO = "SERVICIO_LOCAL_CREATRASLADO";

    // ASIGNACION
    public static final String SERVICIO_LOCAL_CREA_ASIGNACION = "SERVICIO_LOCAL_CREA_ASIGNACION";
    public static final String SERVICIO_LOCAL_GET_ASIGNACION = "SERVICIO_LOCAL_GET_ASIGNACION";
    public static final String SERVICIO_LOCAL_MOD_ASIGNACION = "SERVICIO_LOCAL_MOD_ASIGNACION";
    public static final String SERVICIO_LOCAL_MOD_DET_ASIGNACION = "SERVICIO_LOCAL_MOD_DET_ASIGNACION";

    // PROMOCIONALES
    public static final String SERVICIO_LOCAL_CREAPROMOCIONAL = "SERVICIO_LOCAL_CREAPROMOCIONAL";
    public static final String SERVICIO_LOCAL_MODPROMOCIONAL = "SERVICIO_LOCAL_MODPROMOCIONAL";
    public static final String SERVICIO_LOCAL_GETPROMOCIONAL = "SERVICIO_LOCAL_GETPROMOCIONAL";
    public static final String SERVICIO_LOCAL_DELPROMOCIONAL = "SERVICIO_LOCAL_DELPROMOCIONAL";
    public static final String SERVICIO_LOCAL_INGRESO_SALIDA = "SERVICIO_LOCAL_INGRESO_SALIDA";
    public static final String SERVICIO_LOCAL_GET_CONSULTA_PRODUCTOS_PROM = "SERVICIO_LOCAL_GET_CONSULTA_PRODUCTOS_PROM";
    
    // para informaci\u00F3n de vendedores x dts
    public static final String SERVICIO_LOCAL_GETVENDXDTS = "SERVICIO_LOCAL_GETVENDXDTS";

    // PARA INFORMACION DE HISTORICO
    public static final String SERVICIO_LOCAL_GETHISTORICO = "SERVICIO_LOCAL_GETHISTORICO";
    public static final String SERVICIO_LOCAL_GET_HISTORICOPROMO = "SERVICIO_LOCAL_GET_HISTORICOPROMO";

    // PARA ACEPTAR RECHAZAR SOLICITUD
    public static final String SERVICIO_LOCAL_ACEPTASOLICITUD = "SERVICIO_LOCAL_ACEPTASOLICITUD";

    // PARA CONFIGURACION DE DISPOSITIVOS
    public static final String SERVICIO_LOCAL_CREADISPOSITIVO = "SERVICIO_LOCAL_CREADISPOSITIVO";
    public static final String SERVICIO_LOCAL_MOD_DISPOSITIVO = "SERVICIO_LOCAL_MOD_DISPOSITIVO";
    public static final String SERVICIO_LOCAL_GETDISPOSITIVO = "SERVICIO_LOCAL_GETDISPOSITIVO";

    // PARA CONFIGURAR TIPO DE TRANSACCIONES
    public static final String SERVICIO_LOCAL_CREATIPOTRANSACCION = "SERVICIO_LOCAL_CREATIPOTRANSACCION";
    public static final String SERVICIO_LOCAL_MODIFICATIPOTRANSACCION = "SERVICIO_LOCAL_MODIFICATIPOTRANSACCION";
    public static final String SERVICIO_LOCAL_GETTIPOTRANSACCION = "SERVICIO_LOCAL_GETTIPOTRANSACCION";

    // PARA CONFIGURACION DE LOG
    public static final String SERVICIO_LOCAL_CREALOG = "SERVICIO_LOCAL_CREALOG";

    // PARA CREACI\u00F3N DE JORNADAS
    public static final String SERVICIO_LOCAL_CREA_JORNADA = "SERVICIO_LOCAL_CREA_JORNADA";
    public static final String SERVICIO_LOCAL_MOD_JORNADA = "SERVICIO_LOCAL_MOD_JORNADA";
    public static final String SERVICIO_LOCAL_GET_JORNADA = "SERVICIO_LOCAL_GET_JORNADA";
    
    public static final String SERVICIO_LOCAL_ASIGNA_FECHA_JOR = "SERVICIO_LOCAL_ASIGNA_FECHA_JOR";
    public static final String SERVICIO_LOCAL_GET_FECHA_JOR = "SERVICIO_LOCAL_GET_FECHA_JOR";

    // PARA ASIGNACIONES DE VENDEDOR A DTS
    public static final String SERVICIO_LOCAL_ASIGNA_VENDEDOR_DTS = "SERVICIO_LOCAL_ASIGNA_VENDEDOR_DTS";
    public static final String SERVICIO_LOCAL_GET_VENDEDOR_DTS = "SERVICIO_LOCAL_GET_VENDEDOR_DTS";
    public static final String SERVICIO_LOCAL_BAJA_VENDEDOR_DTS = "SERVICIO_LOCAL_BAJA_VENDEDOR_DTS";
    public static final String SERVICIO_LOCAL_MOD_VEND_DTS = "SERVICIO_LOCAL_MOD_VEND_DTS";

    // PARA OFERTA COMERCIAL
    public static final String SERVICIO_LOCAL_CREA_OFERTA_CAMPANIA = "SERVICIO_LOCAL_CREA_OFERTA_CAMPANIA";
    public static final String SERVICIO_LOCAL_GET_OFERTA_CAMPANIA = "SERVICIO_LOCAL_GET_OFERTA_CAMPANIA";
    public static final String SERVICIO_LOCAL_MOD_OFERTA_CAMPANIA = "SERVICIO_LOCAL_MOD_OFERTA_CAMPANIA";
    public static final String SERVICIO_LOCAL_GET_OFERTA_CAMPANIA_MOVIL = "SERVICIO_LOCAL_GET_OFERTA_CAMPANIA_MOVIL";

    public static final String SERVICIO_LOCAL_ASIGNA_PROMO_CAMPANIA = "SERVICIO_LOCAL_ASIGNA_PROMO_CAMPANIA";
    public static final String SERVICIO_LOCAL_GET_PROMO_CAMPANIA = "SERVICIO_LOCAL_GET_PROMO_CAMPANIA";

    // REGISTRAR VISITA PDV
    public static final String SERVICIO_LOCAL_REGISTRA_VISITA = "SERVICIO_LOCAL_REGISTRA_VISITA";
    public static final String SERVICIO_LOCAL_GETVISITA = "SERVICIO_LOCAL_GETVISITA";

    // PARA CONDICIONES DE CAMPAÑA
    public static final String SERVICIO_LOCAL_CREA_CONDICION_CAMPANIA = "SERVICIO_LOCAL_CREA_CONDICION_CAMPANIA";
    public static final String SERVICIO_LOCAL_GET_CONDICION_CAMPANIA = "SERVICIO_LOCAL_GET_CONDICION_CAMPANIA";
    public static final String SERVICIO_LOCAL_MOD_CONDICION_CAMPANIA = "SERVICIO_LOCAL_MOD_CONDICION_CAMPANIA";

    // PARA CONDICIONES DE OFERTA
    public static final String SERVICIO_LOCAL_CREA_CONDICION_OFERTA = "SERVICIO_LOCAL_CREA_CONDICION_OFERTA";
    public static final String SERVICIO_LOCAL_GET_CONDICION_OFERTA = "SERVICIO_LOCAL_GET_CONDICION_OFERTA";
    public static final String SERVICIO_LOCAL_MOD_CONDICION_OFERTA = "SERVICIO_LOCAL_MOD_CONDICION_OFERTA";
    public static final String SERVICIO_LOCAL_GET_CONDICION_OFERTA_MASIVO = "SERVICIO_LOCAL_GET_CONDICION_OFERTA_MASIVO";

    // FICHA CLIENTE
    public static final String SERVICIO_LOCAL_GET_FICHACLIENTE = "SERVICIO_LOCAL_GET_FICHACLIENTE";
    public static final String SERVICIO_LOCAL_CREAR_FICHACLIENTE_SCL = "SERVICIO_LOCAL_CREAR_FICHACLIENTE_SCL";

    // ADJUNTO GESTION
    public static final String SERVICIO_LOCAL_CARGA_ADJUNTO = "SERVICIO_LOCAL_CARGA_ADJUNTO";
    public static final String SERVICIO_LOCAL_GET_ADJUNTO = "SERVICIO_LOCAL_GET_ADJUNTO";
    public static final String SERVICIO_LOCAL_DEL_ADJUNTO = "SERVICIO_LOCAL_DEL_ADJUNTO";

    // ALTA PREPAGO
    public static final String SERVICIO_LOCAL_CREA_ALTAPREPAGO = "SERVICIO_LOCAL_CREA_ALTAPREPAGO";

    // VENTAS RUTA
    public static final String SERVICIO_LOCAL_CREA_VENTARUTA = "SERVICIO_LOCAL_CREA_VENTARUTA";
    public static final String SERVICIO_LOCAL_GET_VENTARUTA = "SERVICIO_LOCAL_GET_VENTARUTA";
    public static final String SERVICIO_LOCAL_GET_VENTADETALLE = "SERVICIO_LOCAL_GET_VENTADETALLE";

    // TIPO FOLIO
    public static final String FOLIO_MANUAL = "FOLIO_MANUAL";

    // CUENTA BANCARIAS
    public static final String SERVICIO_LOCAL_CREA_CUENTA = "SERVICIO_LOCAL_CREA_CUENTA";
    public static final String SERVICIO_LOCAL_MOD_CUENTA = "SERVICIO_LOCAL_MOD_CUENTA";
    public static final String SERVICIO_LOCAL_GET_CUENTA = "SERVICIO_LOCAL_GET_CUENTA";

    // REMESAS
    public static final String SERVICIO_LOCAL_CREA_REMESA = "SERVICIO_LOCAL_CREA_REMESA";
    public static final String SERVICIO_LOCAL_MOD_REMESA = "SERVICIO_LOCAL_MOD_REMESA";
    public static final String SERVICIO_LOCAL_GET_REMESA = "SERVICIO_LOCAL_GET_REMESA";
    
    // SINCRONIZACION
    public static final String SERVICIO_LOCAL_CREA_SINCRONIZACION = "SERVICIO_LOCAL_CREA_SINCRONIZACION";
    public static final String SERVICIO_LOCAL_GET_SINCRONIZACION = "SERVICIO_LOCAL_GET_SINCRONIZACION";
    public static final String SERVICIO_LOCAL_GET_FALTASINC = "SERVICIO_LOCAL_GET_FALTASINC";

    // PARA CREACI\u00F3N DE JORNADAS MASIVAS
    public static final String SERVICIO_LOCAL_CREA_JORNADA_MAS = "SERVICIO_LOCAL_CREA_JORNADA_MAS";
    public static final String SERVICIO_LOCAL_MOD_JORNADA_MAS = "SERVICIO_LOCAL_MOD_JORNADA_MAS";
    public static final String SERVICIO_LOCAL_GET_JORNADA_MAS = "SERVICIO_LOCAL_GET_JORNADA_MAS";

    // VALIDA VENDEDOR
    public static final String SERVICIO_LOCAL_VALIDA_VENDEDOR = "SERVICIO_LOCAL_VALIDA_VENDEDOR";

    // PARA INFORMACION DE REPORTES
    public static final String SERVICIO_LOCAL_GETREPORTECUMPLIMIENTOVISITA = "SERVICIO_LOCAL_GETREPORTECUMPLIMIENTOVISITA";
    public static final String SERVICIO_LOCAL_GETREPORTECUMPLIMIENTOVENTA = "SERVICIO_LOCAL_GETREPORTECUMPLIMIENTOVENTA";
    public static final String SERVICIO_LOCAL_GETCOUNTCUMPLIMIENTOVENTA = "SERVICIO_LOCAL_GETCOUNTCUMPLIMIENTOVENTA";
    public static final String SERVICIO_LOCAL_GETREPORTEINVENTARIOVENDIDO = "SERVICIO_LOCAL_GETREPORTEINVENTARIOVENDIDO";
    public static final String SERVICIO_LOCAL_GETRESUMENINVENTARIOVENDIDO = "SERVICIO_LOCAL_GETRESUMENINVENTARIOVENDIDO";
    public static final String SERVICIO_LOCAL_GETREPORTEEFECTIVIDADVENTA = "SERVICIO_LOCAL_GETREPORTEEFECTIVIDADVENTA";
    public static final String SERVICIO_LOCAL_GET_REPORTEPDV = "SERVICIO_LOCAL_GET_REPORTEPDV";
    public static final String SERVICIO_LOCAL_GET_REPORTE_INVJORNADA = "SERVICIO_LOCAL_GET_REPORTE_INVJORNADA";

    // REPORTE
    public static final String SERVICIO_LOCAL_COUNT_CONTROLPRECIOS = "SERVICIO_LOCAL_COUNT_CONTROLPRECIOS";
    public static final String SERVICIO_LOCAL_GET_CONTROLPRECIOS = "SERVICIO_LOCAL_GET_CONTROLPRECIOS";
    public static final String SERVICIO_LOCAL_CONSULTA_NUM_RECARGA = "SERVICIO_LOCAL_CONSULTA_NUM_RECARGA";
    public static final String SERVICIO_LOCAL_REPORTE_XZ = "SERVICIO_LOCAL_REPORTE_XZ";
    public static final String SERVICIO_LOCAL_GET_SALDOPAYMENT = "SERVICIO_LOCAL_GET_SALDOPAYMENT";
    public static final String SERVICIO_LOCAL_GET_REPORTE_RECARGAS = "SERVICIO_LOCAL_GET_REPORTE_RECARGAS";

    public static final String SERVICIO_LOCAL_GET_REPORTE_DEBE = "SERVICIO_LOCAL_GET_REPORTE_DEBE";
    public static final String SERVICIO_LOCAL_GET_REPORTE_HABER = "SERVICIO_LOCAL_GET_REPORTE_HABER";
    public static final String SERVICIO_LOCAL_GET_REPORTE_RESUMEN = "SERVICIO_LOCAL_GET_REPORTE_RESUMEN";
    public static final String SERVICIO_LOCAL_POST_REPORTE_RESUMEN = "SERVICIO_LOCAL_POST_REPORTE_RESUMEN";
    
    // PARA FOLIOS FS
    public static final String SERVICIO_LOCAL_RESERVA_FOLIOFS = "SERVICIO_LOCAL_RESERVA_FOLIOFS";
    public static final String SERVICIO_LOCAL_GET_FOLIOFS = "SERVICIO_LOCAL_GET_FOLIOFS";

    // VALIDA SERIES
    public static final String SERVICIO_LOCAL_VALIDA_SERIES = "SERVICIO_LOCAL_VALIDA_SERIES";

    // ANULACIONES
    public static final String SERVICIO_LOCAL_CREA_ANULACION = "SERVICIO_LOCAL_CREA_ANULACION";
    public static final String SERVICIO_LOCAL_GET_ANULACION = "SERVICIO_LOCAL_GET_ANULACION";

    public static final String SERVICIO_LOCAL_GET_FOLIOS_SCL = "SERVICIO_LOCAL_GET_FOLIOS_SCL";
    public static final String SERVICIO_LOCAL_GET_OFICINAS_SCL = "SERVICIO_LOCAL_GET_OFICINAS_SCL";

    public static final String SERVICIO_LOCAL_ASOCIA_RUTAPDV = "SERVICIO_LOCAL_ASOCIA_RUTAPDV";
    public static final String SERVICIO_LOCAL_ELIMINA_RUTAPDV = "SERVICIO_LOCAL_ELIMINA_RUTAPDV";

    public static final String SERVICIO_LOCAL_GETRESUMENDEUDA = "SERVICIO_LOCAL_GET_RESUMENDEUDA";
    public static final String SERVICIO_LOCAL_GET_TRANSACCIONES_DEUDA = "SERVICIO_LOCAL_GET_TRANSACCIONES_DEUDA";
    
    //VENTAS FACTURACION ELECTRONICA

    // VALIDA VENDEDOR
    public static final String SERVICIO_LOCAL_GET_VENTA_FE= "SERVICIO_LOCAL_GET_VENTA_FE";
    
    // VENTAS valida portabilidad
    public static final String SERVICIO_LOCAL_VALIDA_PORTABILIDAD = "SERVICIO_LOCAL_VALIDA_PORTABILIDAD";
    public static final int METODO_COUNT = 4;
    
    //asociacion articulo precio
    public static final String SERVICIO_LOCAL_CREA_ARTICULO_PRECIO = "SERVICIO_LOCAL_CREA_ARTICULO_PRECIO";
    public static final String SERVICIO_LOCAL_MOD_ARTICULO_PRECIO = "SERVICIO_LOCAL_MOD_ARTICULO_PRECIO";
    public static final String SERVICIO_LOCAL_GET_ARTICULO_PRECIO = "SERVICIO_LOCAL_GET_ARTICULO_PRECIO";
    
}
